Models/Customer.cs
namespace DangHoangQuanBTH2.Models
{
    public class Customer 
    {
        public string CustomerID {get; set;}
        public string CustomerName {get; set;}
    }
}

Models/Employee.cs
using System.ComponentModel.DataAnnotations;
namespace DangHoangQuanBTH2.Models;

public class Employee
{
    [Key]
    public string EmployeeID {get; set;}
    public string EmployeeName {get; set;}
    public string Address {get; set;}
}

Models/ErrorViewModel.cs
namespace DangHoangQuanBTH2.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Person.cs
namespace DangHoangQuanBTH2.Models
{
    public class Person 
    {
        public string PersonID {get; set;}
        public string PersonName{ get;set;}
    }
}

Models/Student.cs
namespace DangHoangQuanBTH2.Models
{
    public class Student
    {
        public string StudentID { get;set;}
        public string StudentName {get;set;}
    }
}

Controllers/CustomerController.cs
using DangHoangQuanBTH2.Data;
using DangHoangQuanBTH2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;

namespace DangHoangQuanBTH2.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CustomerController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var model = await _context.Customers.ToListAsync();
            return View(model);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Customer cus)
        {
            if(ModelState.IsValid)
            {
                _context.Add(cus);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cus);
        }
    }
}

Controllers/EmployeeController.cs
using DangHoangQuanBTH2.Data;
using DangHoangQuanBTH2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;

namespace DangHoangQuanBTH2.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly ApplicationDbContext _context;
        public EmployeeController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var model = await _context.Employees.ToListAsync();
            return View(model);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Employee ep)
        {
            if(ModelState.IsValid)
            {
                _context.Add(ep);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ep);
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DangHoangQuanBTH2.Models;

namespace DangHoangQuanBTH2.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/PersonController.cs
using DangHoangQuanBTH2.Data;
using DangHoangQuanBTH2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;

namespace DangHoangQuanBTH2.Controllers
{
    public class PersonController : Controller
    {
        private readonly ApplicationDbContext _context;
        public PersonController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var model = await _context.People.ToListAsync();
            return View(model);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Person ps)
        {
            if(ModelState.IsValid)
            {
                _context.Add(ps);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ps);
        }
    }
}

Controllers/StudentController.cs
using DangHoangQuanBTH2.Data;
using DangHoangQuanBTH2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;

namespace DangHoangQuanBTH2.Controllers
{
    public class StudentController : Controller
    {
        private readonly ApplicationDbContext _context;
        public StudentController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var model = await _context.Students.ToListAsync();
            return View(model);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Student std)
        {
            if (ModelState.IsValid)
            {
                _context.Add(std);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(std);
        }

        private bool StudentExists(string id)
        {
            return _context.Students.Any(e => e.StudentID == id);
        }
        // Get: Student/edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                // return NotFound();
                return View("NotFound");

            }

            var student = await _context.Students.FindAsync(id);
            if (student == null)
            {
                // return NotFound();
                return View("NotFound");
            }
            return View(student);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("StudentID,StudentName")] Student std)
        {
            if (id != std.StudentID)
            {
                // return NotFound();
                return View("NotFound");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(std);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(std.StudentID))
                    {
                        // return NotFound();
                        return View("NotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(std);
        }
        // POST: Product/Delete/5
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var std = await _context.Students.FindAsync(id);
            _context.Students.Remove(std);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }


}

Views/Customer/Create.cshtml
@model DangHoangQuanBTH2.Models.Customer
@{
    string id = @Guid.NewGuid().ToString("N");
}
<form asp-action="Create" method="post" class="col-6">
    <input type="hidden" asp-for="CustomerID" value=@id>
    <div class="mb-3">
        <label for="std-name" class="form-label">Customer Name: </label>
        <input type="text" class="form-control" id="std-name" asp-for="CustomerName">
  </div>
  <button type="submit" class="btn btn-succcess"> Submit</button>
</form>

Views/Customer/Index.cshtml
@model IEnumerable<DangHoangQuanBTH2.Models.Customer>
    <p>
        <a class="btn btn-success" asp-action="Create">Createa new Customer</a>
    
    </p>
    <table class="table table-all" >
        <tr>
            <th>Customer Id</th>
            <th>Customer Name</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m=> item.CustomerID)</td>
                <td>@Html.DisplayFor(m=> item.CustomerName)</td>
            </tr>
        }
        
    </table>

Views/Employee/Create.cshtml
@model DangHoangQuanBTH2.Models.Employee
@{
    string id = @Guid.NewGuid().ToString("N");
}
<form asp-action="Create" method="post" class="col-6">
    <input type="hidden" asp-for="EmployeeID" value=@id>
    <div class="mb-3">
        <label for="std-name" class="form-label">Employee Name: </label>
        <input type="text" class="form-control" id="std-name" asp-for="EmployeeName">
  </div>
  <button type="submit" class="btn btn-succcess"> Submit</button>
</form>

Views/Employee/Index.cshtml
@model IEnumerable<DangHoangQuanBTH2.Models.Employee>
@{
    ViewData["Title"]="Index";
}
    <p>
        <a class="btn btn-success" asp-action="Create">Createa new Employee</a>
    
    </p>
    <table class="table table-all" >
        <tr>
            <th>Employee Id</th>
            <th>Employee Name</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m=> item.EmployeeID)</td>
                <td>@Html.DisplayFor(m=> item.EmployeeName)</td>
            </tr>
        }
        
    </table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Person/Create.cshtml
@model DangHoangQuanBTH2.Models.Person
@{
    string id = @Guid.NewGuid().ToString("N");
}
<form asp-action="Create" method="post" class="col-6">
    <input type="hidden" asp-for="PersonID" value=@id>
    <div class="mb-3">
        <label for="std-name" class="form-label">Person Name: </label>
        <input type="text" class="form-control" id="std-name" asp-for="PersonName">
  </div>
  <button type="submit" class="btn btn-succcess"> Submit</button>
</form>

Views/Person/Index.cshtml
@model IEnumerable<DangHoangQuanBTH2.Models.Person>
    <p>
        <a class="btn btn-success" asp-action="Create">Createa new Person</a>
    
    </p>
    <table class="table table-all" >
        <tr>
            <th>Person Id</th>
            <th>Person Name</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m=> item.PersonID)</td>
                <td>@Html.DisplayFor(m=> item.PersonName)</td>
            </tr>
        }
        
    </table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DangHoangQuanBTH2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DangHoangQuanBTH2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DangHoangQuanBTH2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">Person</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DangHoangQuanBTH2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Student/Create.cshtml
@model DangHoangQuanBTH2.Models.Student
@{
    string id = @Guid.NewGuid().ToString("N");
}
<form asp-action="Create" method="post" class="col-6">
    <input type="hidden" asp-for="StudentID" value=@id>
    <div class="mb-3">
        <label for="std-name" class="form-label">Student Name: </label>
        <input type="text" class="form-control" id="std-name" asp-for="StudentName">
  </div>
  <button type="submit" class="btn btn-succcess"> Submit</button>
</form>

Views/Student/Delete.cshtml
@model DangHoangQuanBTH2.Models.Student

@{
    ViewData["Title"] = "Delete";

}

<h3>Bạn có muốn xóa thông tin Sinh viên?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StudentName):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StudentName)
        </dd>
    </dl>

<form asp-action="Delete">
    <input type="hidden" asp-for="StudentID" />
    <input type="submit" value="Delete" class="btn btn-danger" />
    <a class="btn btn-success" asp-action="Index">Danh sách Sinh viên</a>
</form>
</div>

Views/Student/Edit.cshtml
@model DangHoangQuanBTH2.Models.Student
@{
    ViewData["Title"] = "Edit";

}
<h4>Sửa thông tin Sinh viên</h4>
<hr />
<div class ="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-sumary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StudentID" />
            <div class="form-group">
                <label asp-for="StudentName"  class="control-label"></label>
                <input asp-for="StudentName" class="form-control" />
                <span asp-validation-for="StudentName" class="text-danger"></span>

            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a class="btn btn-success" asp-action="Index">Danh sach sinh vien</a>

            </div>
        </form>
    </div>

</div>
@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptPartial");}
}

Views/Student/index.cshtml
@model IEnumerable<DangHoangQuanBTH2.Models.Student>
    <p>
        <a class="btn btn-success" asp-action="Create">Createa new Student</a>
    
    </p>
    <table class="table table-all" >
        <tr>
            <th>Student Id</th>
            <th>Student Name</th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m=> item.StudentID)</td>
                <td>@Html.DisplayFor(m=> item.StudentName)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.StudentID">Sửa</a>
                    <a asp-action="Delete" asp-route-id="@item.StudentID">Xóa</a>
                </td>
            </tr>
        }
        
    </table>